# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Desfio Intercorp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Desfio Intercorp
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'FBSDKLoginKit'
  pod 'Firebase/Database'

  target 'Desfio IntercorpTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
